spring:
  profiles:
    active: local 
  output:
    ansi:
      enabled: never
  threads:
    virtual:
      enabled: true  

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL:}
    username: ${DATASOURCE_USERNAME:}
    password: ${DATASOURCE_PASSWORD:}
    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
      pool-name: BrewFlow-HikariCP
      connection-timeout: 10000

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true  
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com

mybatis:
  type-aliases-package: com.brewflow.api.domain
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
    jdbc-type-for-null: "NULL"
  mapper-locations: classpath:mapper/**/*.xml

springdoc:
  api-docs:
    enabled: true
  packages-to-scan: com.brewflow.api.controller
  swagger-ui:
    path: /api.html

custom:
  jwt:
    key-str: ${JWT_SECRET_KEY:default_key_here}
    issuer: BrewFlow
    expiration: 1800000
    refresh-expiration: 604800000
    renewal-limit: 10

logging:
  level:
    root: WARN
    com.brewflow.api: DEBUG
    org.springframework.web: INFO
    com.brewflow.api.mapper: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      # 로컬용 (배포 시 prod에서 never로 덮어쓰기) 
      show-details: always  

server:
  port: ${SERVER_PORT:8080}

file:
  upload-path: ${FILE_UPLOAD_PATH:uploads/}